### ISSUE TITLE
"orkestra" is not recognized as an internal or external command

### ISSUE THREAD

**Issue by arthusu** [BitTheByte/Orkestra#3]
When I try to upload a file I get this error in the console.

![2020-10-29 19_24_48-Administrador_ Windows PowerShell](https://user-images.githubusercontent.com/12725208/97652772-70466480-1a1c-11eb-8134-53cc331a4d1b.png)

**Comment by BitTheByte** [comment]
Hello @arthusu 

This should be fixed. sync the codebase and try again

**Comment by arthusu** [comment]
has been fixed, thank you very much.
